# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'browser.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(603, 522)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget{\n"
"    color: rgb(221, 221, 221);\n"
"    font: 10pt \"HarmonyOS Sans SC\";\n"
"    background-color: rgb(40, 44, 52);\n"
"}\n"
"/*Button */\n"
"QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 5px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}\n"
"\n"
"/*LineEdit */\n"
"QLineEdit {\n"
"    background-color: rgb(33, 37, 43);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(33, 37, 43);\n"
"    padding-left: 10px;\n"
"    selection-color: rgb(255, 255, 255);\n"
"    selection-background-color: rgb(111, 168, 220);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}\n"
"\n"
"/* RadioButton */\n"
"QRadioButton::indicator {\n"
"    border: 3px solid rgb(52, 59, 72);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background: rgb(44, 49, 60);\n"
"}\n"
"QRadioButton::indicator:hover {\n"
"    border: 3px solid rgb(58, 66, 81);\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    background: 3px solid rgb(94, 106, 130);\n"
"    border: 3px solid rgb(52, 59, 72);    \n"
"}\n"
"/*CheckBox */\n"
"QCheckBox::indicator {\n"
"    border: 3px solid rgb(52, 59, 72);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background: rgb(44, 49, 60);\n"
"}\n"
"QCheckBox::indicator:hover {\n"
"    border: 3px solid rgb(58, 66, 81);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    background: 3px solid rgb(52, 59, 72);\n"
"    border: 3px solid rgb(52, 59, 72);    \n"
"    background-image: url(:/icons/images/icons/cil-check-alt.png);\n"
"}\n"
"\n"
"/*  QTabBar  */\n"
"QTabWidget{\n"
"    background-color: rgb(40, 44, 52);\n"
"}\n"
"QTabBar{\n"
"  text-transform: uppercase;\n"
"  font-weight: bold;\n"
"  background-color: rgb(40, 44, 52);\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"  max-width:150px;\n"
"  min-width:150px;\n"
"  max-height:30px;\n"
"  min-height:30px;\n"
"  border:0px;\n"
"}\n"
"\n"
"QTabBar::tab:bottom,QTabBar::tab:top{\n"
"  padding: 3px;\n"
"  height: 30px;\n"
"}\n"
"\n"
"QTabBar::tab:left,QTabBar::tab:right{\n"
"  padding: 3px;\n"
"  width: 30px;\n"
"}\n"
"\n"
"QTabBar::tab:top:selected,\n"
"QTabBar::tab:top:hover {\n"
"  color: rgb(109, 158, 235);\n"
"  border-bottom: 3px solid rgb(109, 158, 235);\n"
"}\n"
"\n"
"QTabBar::tab:bottom:selected,\n"
"QTabBar::tab:bottom:hover {\n"
"  color:rgb(109, 158, 235);\n"
"  border-top: 3px solid rgb(109, 158, 235);\n"
"}\n"
"\n"
"QTabBar::tab:right:selected,\n"
"QTabBar::tab:right:hover {\n"
"  color: rgb(109, 158, 235);\n"
"  border-left: 3px solid rgb(109, 158, 235);\n"
"}\n"
"\n"
"QTabBar::tab:left:selected,\n"
"QTabBar::tab:left:hover {\n"
"  color: rgb(109, 158, 235);\n"
"  border-right: 3px solid rgb(109, 158, 235);\n"
"}\n"
"\n"
"QTabBar::close-button {\n"
"  image: url(:/icons/images/icons/close.svg);\n"
"  background-color:  rgb(40, 44, 52);\n"
"  border-radius: 10px; \n"
"}\n"
"\n"
"QTabBar::close-button:hover {\n"
"    background-color: rgb(253, 84, 63);\n"
"}\n"
"QTabBar::close-button:pressed {\n"
"    background-color: rgb(196, 58, 43);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.home = QtWidgets.QPushButton(self.centralwidget)
        self.home.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.home.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/icons/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.home.setIcon(icon)
        self.home.setAutoDefault(False)
        self.home.setObjectName("home")
        self.horizontalLayout_2.addWidget(self.home)
        self.backward = QtWidgets.QPushButton(self.centralwidget)
        self.backward.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.backward.setFont(font)
        self.backward.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/images/icons/backward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.backward.setIcon(icon1)
        self.backward.setIconSize(QtCore.QSize(20, 20))
        self.backward.setFlat(False)
        self.backward.setObjectName("backward")
        self.horizontalLayout_2.addWidget(self.backward)
        self.forward = QtWidgets.QPushButton(self.centralwidget)
        self.forward.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.forward.setFont(font)
        self.forward.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/images/icons/forward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.forward.setIcon(icon2)
        self.forward.setIconSize(QtCore.QSize(20, 20))
        self.forward.setFlat(False)
        self.forward.setObjectName("forward")
        self.horizontalLayout_2.addWidget(self.forward)
        self.refresh = QtWidgets.QPushButton(self.centralwidget)
        self.refresh.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.refresh.setFont(font)
        self.refresh.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/images/icons/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refresh.setIcon(icon3)
        self.refresh.setIconSize(QtCore.QSize(14, 14))
        self.refresh.setFlat(False)
        self.refresh.setObjectName("refresh")
        self.horizontalLayout_2.addWidget(self.refresh)
        self.website_input = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.website_input.sizePolicy().hasHeightForWidth())
        self.website_input.setSizePolicy(sizePolicy)
        self.website_input.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.website_input.setFont(font)
        self.website_input.setObjectName("website_input")
        self.horizontalLayout_2.addWidget(self.website_input)
        self.visit = QtWidgets.QPushButton(self.centralwidget)
        self.visit.setMinimumSize(QtCore.QSize(60, 0))
        self.visit.setMaximumSize(QtCore.QSize(60, 25))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.visit.setFont(font)
        self.visit.setObjectName("visit")
        self.horizontalLayout_2.addWidget(self.visit)
        self.get_xpath = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.get_xpath.setFont(font)
        self.get_xpath.setObjectName("get_xpath")
        self.horizontalLayout_2.addWidget(self.get_xpath)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.web_tab = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.web_tab.setFont(font)
        self.web_tab.setTabPosition(QtWidgets.QTabWidget.North)
        self.web_tab.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.web_tab.setElideMode(QtCore.Qt.ElideNone)
        self.web_tab.setUsesScrollButtons(True)
        self.web_tab.setTabsClosable(True)
        self.web_tab.setMovable(True)
        self.web_tab.setObjectName("web_tab")
        self.verticalLayout_3.addWidget(self.web_tab)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.web_tab.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.home.setToolTip(_translate("MainWindow", "主页"))
        self.backward.setToolTip(_translate("MainWindow", "后退"))
        self.forward.setToolTip(_translate("MainWindow", "前进"))
        self.refresh.setToolTip(_translate("MainWindow", "刷新"))
        self.visit.setText(_translate("MainWindow", "访问"))
        self.get_xpath.setText(_translate("MainWindow", "获取XPath"))
import lib.resources_rc
