# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1400, 1000)
        MainWindow.setMinimumSize(QtCore.QSize(1400, 1000))
        self.styleSheet = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.styleSheet.setFont(font)
        self.styleSheet.setStyleSheet("/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"\n"
"SET APP STYLESHEET - FULL STYLES HERE\n"
"DARK THEME - DRACULA COLOR BASED\n"
"\n"
"///////////////////////////////////////////////////////////////////////////////////////////////// */\n"
"\n"
"QWidget{\n"
"    color: rgb(221, 221, 221);\n"
"    font: 10pt \"HarmonyOS Sans SC\";\n"
"}\n"
"/*Tooltip */\n"
"QToolTip {\n"
"    color: rgb(221,221,221);\n"
"    background-color: rgba(33, 37, 43);\n"
"    border: 1px solid rgb(44, 49, 58);\n"
"    background-image: none;\n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border-left: 2px solid rgb(111, 168, 220);\n"
"    text-align: left;\n"
"    padding-left: 5px;\n"
"    margin: 0px;\n"
"}\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Bg App */\n"
"#bgApp {    \n"
"    background-color: rgb(40, 44, 52);\n"
"    border: 1px solid rgb(44, 49, 58);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Left Menu */\n"
"#leftMenuBg {    \n"
"    background-color: rgb(33, 37, 43);\n"
"}\n"
"#topLogo {\n"
"    background-color: rgb(33, 37, 43);\n"
"    background-image: url(:/images/images/images/cloud_blue.png);\n"
"    background-position: centered;\n"
"    background-repeat: no-repeat;\n"
"}\n"
"#titleLeftApp { font: 63 12pt \"Segoe UI Semibold\"; }\n"
"#titleLeftDescription { font: 8pt \"Segoe UI\"; color: rgb(109, 158, 235); }\n"
"\n"
"/* MENUS */\n"
"#topMenu .QPushButton {    \n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border-left: 22px solid transparent;\n"
"    background-color: transparent;\n"
"    text-align: left;\n"
"    padding-left: 44px;\n"
"}\n"
"#topMenu .QPushButton:hover {\n"
"    background-color: rgb(40, 44, 52);\n"
"}\n"
"#topMenu .QPushButton:pressed {    \n"
"    background-color: rgb(109, 158, 235);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"#bottomMenu .QPushButton {    \n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border-left: 20px solid transparent;\n"
"    background-color:transparent;\n"
"    text-align: left;\n"
"    padding-left: 44px;\n"
"}\n"
"#bottomMenu .QPushButton:hover {\n"
"    background-color: rgb(40, 44, 52);\n"
"}\n"
"#bottomMenu .QPushButton:pressed {    \n"
"    background-color: rgb(109, 158, 235);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"#leftMenuFrame{\n"
"    border-top: 3px solid rgb(44, 49, 58);\n"
"}\n"
"\n"
"/* Toggle Button */\n"
"#toggleButton {\n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border-left: 20px solid transparent;\n"
"    background-color: rgb(37, 41, 48);\n"
"    text-align: left;\n"
"    padding-left: 44px;\n"
"    color: rgb(113, 126, 149);\n"
"}\n"
"#toggleButton:hover {\n"
"    background-color: rgb(40, 44, 52);\n"
"}\n"
"#toggleButton:pressed {\n"
"    background-color: rgb(109, 158, 235);\n"
"}\n"
"\n"
"/* Title Menu */\n"
"#titleRightInfo { padding-left: 10px; }\n"
"\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Extra Tab */\n"
"#extraLeftBox {    \n"
"    background-color: rgb(44, 49, 58);\n"
"}\n"
"#extraTopBg{    \n"
"    background-color: rgb(109, 158, 235)\n"
"}\n"
"\n"
"/* Icon */\n"
"#extraIcon {\n"
"    background-position: center;\n"
"    background-repeat: no-repeat;\n"
"    background-image: url(:/icons/images/icons/icon_information.svg);\n"
"}\n"
"\n"
"/* Label */\n"
"#extraLabel { color: rgb(255, 255, 255); }\n"
"\n"
"/* Btn Close */\n"
"#extraCloseColumnBtn { background-color: rgba(255, 255, 255, 0); border: none;  border-radius: 5px; }\n"
"#extraCloseColumnBtn:hover { background-color: rgb(253, 84, 63); border-style: solid; border-radius: 4px; }\n"
"#extraCloseColumnBtn:pressed { background-color: rgb(196, 58, 43); border-style: solid; border-radius: 4px; }\n"
"\n"
"/* Extra Content */\n"
"#extraContent{\n"
"    border-top: 3px solid rgb(40, 44, 52);\n"
"}\n"
"\n"
"/* Extra Top Menus */\n"
"#extraTopMenu .QPushButton {\n"
"background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border-left: 22px solid transparent;\n"
"    background-color:transparent;\n"
"    text-align: left;\n"
"    padding-left: 44px;\n"
"}\n"
"#extraTopMenu .QPushButton:hover {\n"
"    background-color: rgb(40, 44, 52);\n"
"}\n"
"#extraTopMenu .QPushButton:pressed {    \n"
"    background-color: rgb(109, 158, 235);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Content App */\n"
"#contentTopBg{    \n"
"    background-color: rgb(33, 37, 43);\n"
"}\n"
"#contentBottom{\n"
"    border-top: 3px solid rgb(44, 49, 58);\n"
"}\n"
"\n"
"/* Top Buttons */\n"
"#rightButtons .QPushButton { background-color: rgba(255, 255, 255, 0); border: none;  border-radius: 5px; }\n"
"#rightButtons .QPushButton:hover { background-color: rgb(44, 49, 57); border-style: solid; border-radius: 4px; }\n"
"#rightButtons .QPushButton:pressed { background-color: rgb(23, 26, 30); border-style: solid; border-radius: 4px; }\n"
"\n"
"/* Theme Settings */\n"
"#extraRightBox { background-color: rgb(44, 49, 58); }\n"
"#themeSettingsTopDetail { background-color: rgb(109, 158, 235); }\n"
"\n"
"/* Bottom Bar */\n"
"#bottomBar { background-color: rgb(44, 49, 58); }\n"
"#bottomBar QLabel { font-size: 8pt; color: rgb(113, 126, 149); padding-left: 10px; padding-right: 10px; padding-bottom: 2px; }\n"
"\n"
"/* CONTENT User  */\n"
"/* MENUS */\n"
"#contentUser .QPushButton {    \n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border-left: 22px solid transparent;\n"
"    background-color:transparent;\n"
"    text-align: left;\n"
"    padding-left: 44px;\n"
"}\n"
"#contentUser .QPushButton:hover {\n"
"    background-color: rgb(40, 44, 52);\n"
"}\n"
"#contentUser .QPushButton:pressed {    \n"
"    background-color: rgb(109, 158, 235);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.styleSheet.setObjectName("styleSheet")
        self.appMargins = QtWidgets.QVBoxLayout(self.styleSheet)
        self.appMargins.setContentsMargins(10, 10, 10, 10)
        self.appMargins.setSpacing(0)
        self.appMargins.setObjectName("appMargins")
        self.bgApp = QtWidgets.QFrame(self.styleSheet)
        self.bgApp.setStyleSheet("")
        self.bgApp.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.bgApp.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bgApp.setObjectName("bgApp")
        self.appLayout = QtWidgets.QHBoxLayout(self.bgApp)
        self.appLayout.setContentsMargins(0, 0, 0, 0)
        self.appLayout.setSpacing(0)
        self.appLayout.setObjectName("appLayout")
        self.leftMenuBg = QtWidgets.QFrame(self.bgApp)
        self.leftMenuBg.setMinimumSize(QtCore.QSize(60, 0))
        self.leftMenuBg.setMaximumSize(QtCore.QSize(60, 16777215))
        self.leftMenuBg.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.leftMenuBg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftMenuBg.setObjectName("leftMenuBg")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.leftMenuBg)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.topLogoInfo = QtWidgets.QFrame(self.leftMenuBg)
        self.topLogoInfo.setMinimumSize(QtCore.QSize(0, 50))
        self.topLogoInfo.setMaximumSize(QtCore.QSize(16777215, 50))
        self.topLogoInfo.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.topLogoInfo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topLogoInfo.setObjectName("topLogoInfo")
        self.topLogo = QtWidgets.QFrame(self.topLogoInfo)
        self.topLogo.setGeometry(QtCore.QRect(10, 5, 42, 42))
        self.topLogo.setMinimumSize(QtCore.QSize(42, 42))
        self.topLogo.setMaximumSize(QtCore.QSize(42, 42))
        self.topLogo.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.topLogo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topLogo.setObjectName("topLogo")
        self.titleLeftApp = QtWidgets.QLabel(self.topLogoInfo)
        self.titleLeftApp.setGeometry(QtCore.QRect(70, 8, 160, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.titleLeftApp.setFont(font)
        self.titleLeftApp.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.titleLeftApp.setObjectName("titleLeftApp")
        self.titleLeftDescription = QtWidgets.QLabel(self.topLogoInfo)
        self.titleLeftDescription.setGeometry(QtCore.QRect(70, 27, 160, 16))
        self.titleLeftDescription.setMaximumSize(QtCore.QSize(16777215, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.titleLeftDescription.setFont(font)
        self.titleLeftDescription.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.titleLeftDescription.setObjectName("titleLeftDescription")
        self.verticalLayout_3.addWidget(self.topLogoInfo)
        self.leftMenuFrame = QtWidgets.QFrame(self.leftMenuBg)
        self.leftMenuFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.leftMenuFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftMenuFrame.setObjectName("leftMenuFrame")
        self.verticalMenuLayout = QtWidgets.QVBoxLayout(self.leftMenuFrame)
        self.verticalMenuLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalMenuLayout.setSpacing(0)
        self.verticalMenuLayout.setObjectName("verticalMenuLayout")
        self.toggleBox = QtWidgets.QFrame(self.leftMenuFrame)
        self.toggleBox.setMaximumSize(QtCore.QSize(16777215, 45))
        self.toggleBox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.toggleBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.toggleBox.setObjectName("toggleBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.toggleBox)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.toggleButton = QtWidgets.QPushButton(self.toggleBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toggleButton.sizePolicy().hasHeightForWidth())
        self.toggleButton.setSizePolicy(sizePolicy)
        self.toggleButton.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.toggleButton.setFont(font)
        self.toggleButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toggleButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toggleButton.setStyleSheet("background-image: url(:/icons/images/icons/unfold.png);")
        self.toggleButton.setText("")
        self.toggleButton.setObjectName("toggleButton")
        self.verticalLayout_4.addWidget(self.toggleButton)
        self.verticalMenuLayout.addWidget(self.toggleBox)
        self.topMenu = QtWidgets.QFrame(self.leftMenuFrame)
        self.topMenu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.topMenu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topMenu.setObjectName("topMenu")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.topMenu)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.btn_instruct = QtWidgets.QPushButton(self.topMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_instruct.sizePolicy().hasHeightForWidth())
        self.btn_instruct.setSizePolicy(sizePolicy)
        self.btn_instruct.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_instruct.setFont(font)
        self.btn_instruct.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_instruct.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_instruct.setStyleSheet("background-image: url(:/icons/images/icons/cil-browser.png);")
        self.btn_instruct.setObjectName("btn_instruct")
        self.verticalLayout_8.addWidget(self.btn_instruct)
        self.btn_run = QtWidgets.QPushButton(self.topMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_run.sizePolicy().hasHeightForWidth())
        self.btn_run.setSizePolicy(sizePolicy)
        self.btn_run.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_run.setFont(font)
        self.btn_run.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_run.setToolTip("")
        self.btn_run.setToolTipDuration(-1)
        self.btn_run.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_run.setStyleSheet("background-image: url(:/icons/images/icons/cil-media-play.png);")
        self.btn_run.setObjectName("btn_run")
        self.verticalLayout_8.addWidget(self.btn_run)
        self.verticalMenuLayout.addWidget(self.topMenu, 0, QtCore.Qt.AlignTop)
        self.bottomMenu = QtWidgets.QFrame(self.leftMenuFrame)
        self.bottomMenu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.bottomMenu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottomMenu.setObjectName("bottomMenu")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.bottomMenu)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.toggleLeftBox = QtWidgets.QPushButton(self.bottomMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toggleLeftBox.sizePolicy().hasHeightForWidth())
        self.toggleLeftBox.setSizePolicy(sizePolicy)
        self.toggleLeftBox.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.toggleLeftBox.setFont(font)
        self.toggleLeftBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toggleLeftBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toggleLeftBox.setStyleSheet("background-image: url(:/icons/images/icons/icon_information.svg);")
        self.toggleLeftBox.setIconSize(QtCore.QSize(50, 16))
        self.toggleLeftBox.setObjectName("toggleLeftBox")
        self.verticalLayout_9.addWidget(self.toggleLeftBox)
        self.verticalMenuLayout.addWidget(self.bottomMenu, 0, QtCore.Qt.AlignBottom)
        self.verticalLayout_3.addWidget(self.leftMenuFrame)
        self.appLayout.addWidget(self.leftMenuBg)
        self.extraLeftBox = QtWidgets.QFrame(self.bgApp)
        self.extraLeftBox.setMinimumSize(QtCore.QSize(0, 0))
        self.extraLeftBox.setMaximumSize(QtCore.QSize(0, 16777215))
        self.extraLeftBox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.extraLeftBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.extraLeftBox.setObjectName("extraLeftBox")
        self.extraColumLayout = QtWidgets.QVBoxLayout(self.extraLeftBox)
        self.extraColumLayout.setContentsMargins(0, 0, 0, 0)
        self.extraColumLayout.setSpacing(0)
        self.extraColumLayout.setObjectName("extraColumLayout")
        self.extraTopBg = QtWidgets.QFrame(self.extraLeftBox)
        self.extraTopBg.setMinimumSize(QtCore.QSize(0, 50))
        self.extraTopBg.setMaximumSize(QtCore.QSize(16777215, 50))
        self.extraTopBg.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.extraTopBg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.extraTopBg.setObjectName("extraTopBg")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.extraTopBg)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.extraTopLayout = QtWidgets.QGridLayout()
        self.extraTopLayout.setContentsMargins(18, -1, 10, -1)
        self.extraTopLayout.setHorizontalSpacing(25)
        self.extraTopLayout.setVerticalSpacing(0)
        self.extraTopLayout.setObjectName("extraTopLayout")
        self.extraCloseColumnBtn = QtWidgets.QPushButton(self.extraTopBg)
        self.extraCloseColumnBtn.setMinimumSize(QtCore.QSize(28, 28))
        self.extraCloseColumnBtn.setMaximumSize(QtCore.QSize(28, 28))
        self.extraCloseColumnBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.extraCloseColumnBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/icons/icon_close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.extraCloseColumnBtn.setIcon(icon)
        self.extraCloseColumnBtn.setIconSize(QtCore.QSize(20, 20))
        self.extraCloseColumnBtn.setObjectName("extraCloseColumnBtn")
        self.extraTopLayout.addWidget(self.extraCloseColumnBtn, 0, 2, 1, 1)
        self.extraIcon = QtWidgets.QFrame(self.extraTopBg)
        self.extraIcon.setMinimumSize(QtCore.QSize(24, 0))
        self.extraIcon.setMaximumSize(QtCore.QSize(24, 24))
        self.extraIcon.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.extraIcon.setFrameShadow(QtWidgets.QFrame.Raised)
        self.extraIcon.setObjectName("extraIcon")
        self.extraTopLayout.addWidget(self.extraIcon, 0, 0, 1, 1)
        self.extraLabel = QtWidgets.QLabel(self.extraTopBg)
        self.extraLabel.setMinimumSize(QtCore.QSize(50, 0))
        self.extraLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.extraLabel.setObjectName("extraLabel")
        self.extraTopLayout.addWidget(self.extraLabel, 0, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.extraTopLayout)
        self.extraColumLayout.addWidget(self.extraTopBg)
        self.extraContent = QtWidgets.QFrame(self.extraLeftBox)
        self.extraContent.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.extraContent.setFrameShadow(QtWidgets.QFrame.Raised)
        self.extraContent.setObjectName("extraContent")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.extraContent)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.extraTopMenu = QtWidgets.QFrame(self.extraContent)
        self.extraTopMenu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.extraTopMenu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.extraTopMenu.setObjectName("extraTopMenu")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.extraTopMenu)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.btn_help = QtWidgets.QPushButton(self.extraTopMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_help.sizePolicy().hasHeightForWidth())
        self.btn_help.setSizePolicy(sizePolicy)
        self.btn_help.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_help.setFont(font)
        self.btn_help.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_help.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_help.setStyleSheet("background-image: url(:/icons/images/icons/cil-description.png);")
        self.btn_help.setObjectName("btn_help")
        self.verticalLayout_11.addWidget(self.btn_help)
        self.verticalLayout_12.addWidget(self.extraTopMenu, 0, QtCore.Qt.AlignTop)
        self.extraCenter = QtWidgets.QFrame(self.extraContent)
        self.extraCenter.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.extraCenter.setFrameShadow(QtWidgets.QFrame.Raised)
        self.extraCenter.setObjectName("extraCenter")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.extraCenter)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.textEdit = QtWidgets.QTextEdit(self.extraCenter)
        self.textEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.textEdit.setStyleSheet("background: transparent;")
        self.textEdit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_10.addWidget(self.textEdit)
        self.verticalLayout_12.addWidget(self.extraCenter)
        self.extraBottom = QtWidgets.QFrame(self.extraContent)
        self.extraBottom.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.extraBottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.extraBottom.setObjectName("extraBottom")
        self.verticalLayout_12.addWidget(self.extraBottom)
        self.extraColumLayout.addWidget(self.extraContent)
        self.appLayout.addWidget(self.extraLeftBox)
        self.contentBox = QtWidgets.QFrame(self.bgApp)
        self.contentBox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.contentBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contentBox.setObjectName("contentBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.contentBox)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.contentTopBg = QtWidgets.QFrame(self.contentBox)
        self.contentTopBg.setMinimumSize(QtCore.QSize(0, 50))
        self.contentTopBg.setMaximumSize(QtCore.QSize(16777215, 50))
        self.contentTopBg.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.contentTopBg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contentTopBg.setObjectName("contentTopBg")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.contentTopBg)
        self.horizontalLayout.setContentsMargins(0, 0, 10, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftBox = QtWidgets.QFrame(self.contentTopBg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftBox.sizePolicy().hasHeightForWidth())
        self.leftBox.setSizePolicy(sizePolicy)
        self.leftBox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.leftBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftBox.setObjectName("leftBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.leftBox)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.titleRightInfo = QtWidgets.QLabel(self.leftBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleRightInfo.sizePolicy().hasHeightForWidth())
        self.titleRightInfo.setSizePolicy(sizePolicy)
        self.titleRightInfo.setMaximumSize(QtCore.QSize(16777215, 45))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.titleRightInfo.setFont(font)
        self.titleRightInfo.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.titleRightInfo.setObjectName("titleRightInfo")
        self.horizontalLayout_3.addWidget(self.titleRightInfo)
        self.horizontalLayout.addWidget(self.leftBox)
        self.rightButtons = QtWidgets.QFrame(self.contentTopBg)
        self.rightButtons.setMinimumSize(QtCore.QSize(0, 28))
        self.rightButtons.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.rightButtons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rightButtons.setObjectName("rightButtons")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.rightButtons)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.userinfoBtn = QtWidgets.QPushButton(self.rightButtons)
        self.userinfoBtn.setMinimumSize(QtCore.QSize(80, 28))
        self.userinfoBtn.setMaximumSize(QtCore.QSize(80, 28))
        self.userinfoBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.userinfoBtn.setStyleSheet("#userinfoBtn { background-color: rgba(255, 255, 255, 0); border: none;  border-radius: 5px; color:rgb(255,255,255);}\n"
"#userinfoBtn:hover { background-color: rgb(109, 158, 235); border-style: solid; border-radius: 4px; }\n"
"#userinfoBtn:pressed { background-color: rgb(79, 128,205); border-style: solid; border-radius: 4px; }")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/images/icons/user.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.userinfoBtn.setIcon(icon1)
        self.userinfoBtn.setIconSize(QtCore.QSize(20, 20))
        self.userinfoBtn.setObjectName("userinfoBtn")
        self.horizontalLayout_2.addWidget(self.userinfoBtn)
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.minimizeAppBtn = QtWidgets.QPushButton(self.rightButtons)
        self.minimizeAppBtn.setMinimumSize(QtCore.QSize(28, 28))
        self.minimizeAppBtn.setMaximumSize(QtCore.QSize(28, 28))
        self.minimizeAppBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.minimizeAppBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/images/icons/icon_minimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimizeAppBtn.setIcon(icon2)
        self.minimizeAppBtn.setIconSize(QtCore.QSize(20, 20))
        self.minimizeAppBtn.setObjectName("minimizeAppBtn")
        self.horizontalLayout_2.addWidget(self.minimizeAppBtn)
        self.maximizeRestoreAppBtn = QtWidgets.QPushButton(self.rightButtons)
        self.maximizeRestoreAppBtn.setMinimumSize(QtCore.QSize(28, 28))
        self.maximizeRestoreAppBtn.setMaximumSize(QtCore.QSize(28, 28))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.maximizeRestoreAppBtn.setFont(font)
        self.maximizeRestoreAppBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.maximizeRestoreAppBtn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/images/icons/icon_maximize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.maximizeRestoreAppBtn.setIcon(icon3)
        self.maximizeRestoreAppBtn.setIconSize(QtCore.QSize(20, 20))
        self.maximizeRestoreAppBtn.setObjectName("maximizeRestoreAppBtn")
        self.horizontalLayout_2.addWidget(self.maximizeRestoreAppBtn)
        self.closeAppBtn = QtWidgets.QPushButton(self.rightButtons)
        self.closeAppBtn.setMinimumSize(QtCore.QSize(28, 28))
        self.closeAppBtn.setMaximumSize(QtCore.QSize(28, 28))
        self.closeAppBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.closeAppBtn.setStyleSheet("#closeAppBtn { background-color: rgba(255, 255, 255, 0); border: none;  border-radius: 5px; }\n"
"#closeAppBtn:hover { background-color: rgb(253, 84, 63); border-style: solid; border-radius: 4px; }\n"
"#closeAppBtn:pressed { background-color: rgb(196, 58, 43); border-style: solid; border-radius: 4px; }")
        self.closeAppBtn.setText("")
        self.closeAppBtn.setIcon(icon)
        self.closeAppBtn.setIconSize(QtCore.QSize(20, 20))
        self.closeAppBtn.setObjectName("closeAppBtn")
        self.horizontalLayout_2.addWidget(self.closeAppBtn)
        self.horizontalLayout.addWidget(self.rightButtons, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_2.addWidget(self.contentTopBg)
        self.contentBottom = QtWidgets.QFrame(self.contentBox)
        self.contentBottom.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.contentBottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contentBottom.setObjectName("contentBottom")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.contentBottom)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.content = QtWidgets.QFrame(self.contentBottom)
        self.content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content.setObjectName("content")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.content)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pagesContainer = QtWidgets.QFrame(self.content)
        self.pagesContainer.setStyleSheet("")
        self.pagesContainer.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.pagesContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pagesContainer.setObjectName("pagesContainer")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.pagesContainer)
        self.verticalLayout_15.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.stackedWidget = QtWidgets.QStackedWidget(self.pagesContainer)
        self.stackedWidget.setMinimumSize(QtCore.QSize(1200, 800))
        self.stackedWidget.setStyleSheet("background: transparent;")
        self.stackedWidget.setObjectName("stackedWidget")
        self.verticalLayout_15.addWidget(self.stackedWidget)
        self.horizontalLayout_4.addWidget(self.pagesContainer)
        self.extraRightBox = QtWidgets.QFrame(self.content)
        self.extraRightBox.setMinimumSize(QtCore.QSize(0, 0))
        self.extraRightBox.setMaximumSize(QtCore.QSize(0, 16777215))
        self.extraRightBox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.extraRightBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.extraRightBox.setObjectName("extraRightBox")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.extraRightBox)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.themeSettingsTopDetail = QtWidgets.QFrame(self.extraRightBox)
        self.themeSettingsTopDetail.setMaximumSize(QtCore.QSize(16777215, 3))
        self.themeSettingsTopDetail.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.themeSettingsTopDetail.setFrameShadow(QtWidgets.QFrame.Raised)
        self.themeSettingsTopDetail.setObjectName("themeSettingsTopDetail")
        self.verticalLayout_7.addWidget(self.themeSettingsTopDetail)
        self.contentUser = QtWidgets.QFrame(self.extraRightBox)
        self.contentUser.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.contentUser.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contentUser.setObjectName("contentUser")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.contentUser)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.topMenus = QtWidgets.QFrame(self.contentUser)
        self.topMenus.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.topMenus.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topMenus.setObjectName("topMenus")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.topMenus)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.btn_logout = QtWidgets.QPushButton(self.topMenus)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_logout.sizePolicy().hasHeightForWidth())
        self.btn_logout.setSizePolicy(sizePolicy)
        self.btn_logout.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_logout.setFont(font)
        self.btn_logout.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_logout.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_logout.setStyleSheet("background-image: url(:/icons/images/icons/cil-account-logout.png);")
        self.btn_logout.setObjectName("btn_logout")
        self.verticalLayout_14.addWidget(self.btn_logout)
        self.verticalLayout_13.addWidget(self.topMenus, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_7.addWidget(self.contentUser)
        self.horizontalLayout_4.addWidget(self.extraRightBox)
        self.verticalLayout_6.addWidget(self.content)
        self.bottomBar = QtWidgets.QFrame(self.contentBottom)
        self.bottomBar.setMinimumSize(QtCore.QSize(0, 22))
        self.bottomBar.setMaximumSize(QtCore.QSize(16777215, 22))
        self.bottomBar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.bottomBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottomBar.setObjectName("bottomBar")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.bottomBar)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.creditsLabel = QtWidgets.QLabel(self.bottomBar)
        self.creditsLabel.setMaximumSize(QtCore.QSize(16777215, 16))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.creditsLabel.setFont(font)
        self.creditsLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.creditsLabel.setObjectName("creditsLabel")
        self.horizontalLayout_5.addWidget(self.creditsLabel)
        self.version = QtWidgets.QLabel(self.bottomBar)
        self.version.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.version.setObjectName("version")
        self.horizontalLayout_5.addWidget(self.version)
        self.frame_size_grip = QtWidgets.QFrame(self.bottomBar)
        self.frame_size_grip.setMinimumSize(QtCore.QSize(20, 0))
        self.frame_size_grip.setMaximumSize(QtCore.QSize(20, 16777215))
        self.frame_size_grip.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_size_grip.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_size_grip.setObjectName("frame_size_grip")
        self.horizontalLayout_5.addWidget(self.frame_size_grip)
        self.verticalLayout_6.addWidget(self.bottomBar)
        self.verticalLayout_2.addWidget(self.contentBottom)
        self.appLayout.addWidget(self.contentBox)
        self.appMargins.addWidget(self.bgApp)
        MainWindow.setCentralWidget(self.styleSheet)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.titleLeftApp.setText(_translate("MainWindow", "OCR&RPA"))
        self.titleLeftDescription.setText(_translate("MainWindow", "By:HUST-AIA-ISE"))
        self.btn_instruct.setToolTip(_translate("MainWindow", "指令编辑"))
        self.btn_instruct.setText(_translate("MainWindow", "指令编辑"))
        self.btn_run.setText(_translate("MainWindow", "运行"))
        self.toggleLeftBox.setText(_translate("MainWindow", "帮助信息"))
        self.extraCloseColumnBtn.setToolTip(_translate("MainWindow", "Close left box"))
        self.extraLabel.setText(_translate("MainWindow", "信息"))
        self.btn_help.setText(_translate("MainWindow", "帮助文档"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'HarmonyOS Sans SC\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#ff79c6;\">OCR&amp;RPA</span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">软件介绍</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; color:#ffffff;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#ff79c6;\">制作单位</span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">HUST-AIA-ISE</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.titleRightInfo.setText(_translate("MainWindow", "RPA自动化执行软件"))
        self.userinfoBtn.setToolTip(_translate("MainWindow", "用户"))
        self.userinfoBtn.setText(_translate("MainWindow", "  用户名"))
        self.minimizeAppBtn.setToolTip(_translate("MainWindow", "最小化"))
        self.maximizeRestoreAppBtn.setToolTip(_translate("MainWindow", "最大化"))
        self.closeAppBtn.setToolTip(_translate("MainWindow", "关闭"))
        self.btn_logout.setText(_translate("MainWindow", "退出登录"))
        self.creditsLabel.setText(_translate("MainWindow", "By：HUST-ISE"))
        self.version.setText(_translate("MainWindow", "v0.0.1"))
import lib.resources_rc
